name: Ciao

on:
  push:

jobs:
  come:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "action_repository" ${{github.action_repository}}
          echo "actor" ${{github.actor}}
          echo "event" ${{github.event}}
          echo "repository" ${{github.repository}}
          echo "repository_owner" ${{github.repository_owner}}
          echo "workflow_ref" ${{github.workflow_ref}}
